lst= list()
lst = ['Apple','Banana','Strawberry']
print(lst)
lst.append('Mango')
print(lst)
lst1 = lst.copy()
print(lst1)
a = lst.count('Apple')
print(a)
lst.extend(lst1)
print(lst)
b = lst.index('Mango')
print(b)
lst.insert(2,'Orange')
print(lst)
lst.pop()
print(lst)
lst.remove('Banana')
print(lst)
lst.remove('Banana')
print(lst)
lst.reverse()
print(lst)
lst.sort()
print(lst)
lst.clear()
print(lst)