s = {"apple","apple","banana","cherry"}
print(s)
for i in s:
    print(i)
if "banana" in s:
    print('Yes')
print("apple" in s)
s.add("mango")   #add single item
print(s)
s.update(["grapes","orange","watermelon"])
print(s)
print(len(s))
s.remove("banana")
print(s)
s.discard("apple")
print(s)
a = s.pop()
print(a)
print(s)
s1 = {"1","2","3"}
s2 = s1.union(s)
print(s2)
s.update(s1)
print(s)
s3 = set(("a","b","c"))
print(s3)
print(type(s3))
s1.add("4")
print(s1)
s4=s1.copy()
print(s4)
s4.add("5")
print(s4)
z = s4.difference(s1)
print(z)
print(s4)
s4.difference_update(s1)
print(s4)
x = s1.intersection(s4)
print(x)
s1.add("78")
print(s1)
s1.intersection_update(s4)
print(s1)
print(s2)
print(s3)
s3.add("2")
w = s2.isdisjoint(s3)
print(w)
s5 = {"1","2","3"}
s6 = {"10", "20","3","1","2","30"}
u = s5.issubset(s6)
print(u)
v = s6.issuperset(s5)
print(v)