t = ("Honda" , "Nissan" , "Suzuki" , "Toyota" , "Honda")
print(t)
print(t[1])
print(t[-1])
print(t[1:3])
print(t[-2:-1])
for i in t:
    print(i)
print(len(t))
t1 = ("Apple",)
print(t1,type(t1))
s = ("Apple")
print(s,type(s))
t2 = t + t1
print(t2)
t3 = tuple(("A","B","C"))
print(t3)
a =t.count("Honda")
print(a)
b = t.index("Toyota")
print(b)